#!/usr/bin/env python3
"""Generate all configuration surfaces from config/options.json.

The committed outputs deliberately remain buildable without Python.  CI runs
this script with --check so a change to defaults, CLI parsing, validation, help,
JSON configuration, or the result-schema config object cannot drift from the
single metadata source.
"""
from __future__ import annotations

import argparse
import copy
import json
import os
import sys
import tempfile
import textwrap
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
METADATA_PATH = ROOT / "config" / "options.json"
SCHEMA_PATH = ROOT / "schema" / "results.schema.json"

GENERATED = {
    ROOT / "include" / "aldous_tsp" / "generated" / "external_oracle_fields.inc": "oracle_fields",
    ROOT / "include" / "aldous_tsp" / "generated" / "solver_options_fields.inc": "solver_fields",
    ROOT / "include" / "aldous_tsp" / "generated" / "run_options_fields.inc": "run_fields",
    ROOT / "include" / "aldous_tsp" / "generated" / "options_schema_version.inc": "schema_version",
    ROOT / "src" / "generated_options.hpp": "header",
    ROOT / "src" / "generated_options_core.cpp": "core",
    ROOT / "src" / "generated_options_cli.cpp": "cli",
    ROOT / "docs" / "generated" / "options.md": "docs",
}

HEADER = "// Generated by scripts/generate_options.py from config/options.json. DO NOT EDIT.\n"


def fail(message: str) -> "NoReturn":
    raise SystemExit(f"option metadata error: {message}")


def load_metadata() -> dict[str, Any]:
    data = json.loads(METADATA_PATH.read_text(encoding="utf-8"))
    if data.get("metadata_version") != 1:
        fail("unsupported metadata_version")
    options = data.get("options")
    if not isinstance(options, list) or not options:
        fail("options must be a nonempty list")
    seen_ids: set[str] = set()
    seen_cli: set[str] = set()
    seen_fields: set[tuple[str, str]] = set()
    seen_json: set[str] = set()
    sections = {entry["id"] for entry in data.get("sections", [])}
    for option in options:
        option_id = option.get("id")
        if not isinstance(option_id, str) or not option_id:
            fail("every option needs a nonempty id")
        if option_id in seen_ids:
            fail(f"duplicate id {option_id}")
        seen_ids.add(option_id)
        if option.get("section") not in sections:
            fail(f"{option_id}: unknown section {option.get('section')}")
        cli = option.get("cli")
        for flag in ([cli] if cli else []) + list(option.get("aliases", [])):
            if not isinstance(flag, str) or not flag.startswith("--"):
                fail(f"{option_id}: invalid CLI flag {flag!r}")
            if flag in seen_cli:
                fail(f"duplicate CLI flag {flag}")
            seen_cli.add(flag)
        if option.get("declare", True):
            struct = option.get("struct")
            member = option.get("member")
            cpp_type = option.get("cpp_type")
            if struct not in {"run", "solver", "oracle"} or not member or not cpp_type:
                fail(f"{option_id}: declared fields need struct/member/cpp_type")
            field = (struct, member)
            if field in seen_fields:
                fail(f"duplicate field {struct}.{member}")
            seen_fields.add(field)
        if option.get("emit_json", True) and option.get("json_key"):
            key = option["json_key"]
            if key in seen_json:
                fail(f"duplicate emitted JSON key {key}")
            seen_json.add(key)
    return data


def cpp_default(option: dict[str, Any]) -> str:
    if "cpp_default" in option:
        return str(option["cpp_default"])
    value = option.get("default")
    cpp_type = option["cpp_type"]
    if cpp_type == "bool":
        return "true" if value else "false"
    if cpp_type == "std::string":
        return json.dumps(str(value))
    if cpp_type == "double":
        if isinstance(value, int):
            return f"{value}.0"
        return repr(float(value))
    if cpp_type == "std::vector<double>":
        return "{}" if not value else "{" + ", ".join(repr(float(x)) for x in value) + "}"
    if cpp_type == "std::optional<int>":
        return "std::nullopt" if value is None else str(int(value))
    return str(value)


def cpp_value(option: dict[str, Any], value: Any) -> str:
    temporary = dict(option)
    temporary.pop("cpp_default", None)
    temporary["default"] = value
    return cpp_default(temporary)


def access(option: dict[str, Any]) -> str:
    struct = option["struct"]
    member = option["member"]
    if struct == "run":
        return f"opt.{member}"
    if struct == "solver":
        return f"opt.solver.{member}"
    if struct == "oracle":
        return f"opt.solver.oracle.cfg.{member}"
    fail(f"{option['id']}: unknown struct")


def default_text(option: dict[str, Any]) -> str | None:
    if option.get("show_default", True) is False:
        return None
    if option.get("action") in {"help", "self_test", "quick", "p_values", "p_range", "p_file"}:
        return None
    if option.get("id") in {"point_seed", "search_seed"}:
        return "--seed"
    value = option.get("default")
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return None
    if isinstance(value, list):
        return ",".join(str(x) for x in value)
    return str(value)


def render_fields(data: dict[str, Any], struct: str) -> str:
    lines = [HEADER.rstrip(), ""]
    for option in data["options"]:
        if not option.get("declare", True) or option.get("struct") != struct:
            continue
        description = str(option.get("help", option["id"]))
        for line in textwrap.wrap(description, width=86):
            lines.append(f"    // {line}")
        lines.append(
            f"    {option['cpp_type']} {option['member']} = {cpp_default(option)};"
        )
    lines.append("")
    return "\n".join(lines)


def render_header() -> str:
    return HEADER + r'''#pragma once

#include "aldous_tsp/config.hpp"

#include <cstdio>
#include <iosfwd>
#include <string>

namespace aldous_tsp {

enum class GeneratedCliParseResult {
    NoMatch,
    Matched,
    Error,
    ExitSuccess,
};

// Generated CLI parser. It is side-effect free except for mutating `opt`,
// setting `self_test`, and writing generated help for --help.
GeneratedCliParseResult parse_generated_cli_option(
    int& index,
    int argc,
    char** argv,
    RunOptions& opt,
    bool& self_test,
    std::string& error);

bool generated_quick_requested(int argc, char** argv, bool& requested, std::string& error);
void apply_generated_cli_defaults(RunOptions& opt);
void apply_generated_quick_preset(RunOptions& opt);
void print_generated_help(FILE* stream, const char* argv0);

// Generated field-local validation. Cross-field and instance-dependent rules
// live in validation.cpp and call this function first.
bool validate_generated_option_ranges(const RunOptions& opt, std::string& error);

// Emits the complete user-controlled configuration object. Runtime resolution
// fields such as oracle_exec_path are appended by results.cpp.
void write_generated_config(std::ostream& out, const RunOptions& opt, const std::string& indent);

} // namespace aldous_tsp
'''


def schema_check_expr(expr: str, constraints: dict[str, Any], label: str, cpp_type: str) -> list[str]:
    lines: list[str] = []
    if cpp_type == "double":
        lines.append(f"    if (!std::isfinite({expr})) {{ error = \"{label} must be finite\"; return false; }}")
    if "minimum" in constraints and "maximum" in constraints:
        minimum = constraints["minimum"]
        maximum = constraints["maximum"]
        lines.append(
            f"    if ({expr} < {repr(minimum)} || {expr} > {repr(maximum)}) "
            f"{{ error = \"{label} must be in [{minimum},{maximum}]\"; return false; }}"
        )
    else:
        if "minimum" in constraints:
            lines.append(f"    if ({expr} < {repr(constraints['minimum'])}) {{ error = \"{label} must be >= {constraints['minimum']}\"; return false; }}")
        if "maximum" in constraints:
            lines.append(f"    if ({expr} > {repr(constraints['maximum'])}) {{ error = \"{label} must be <= {constraints['maximum']}\"; return false; }}")
    if "exclusiveMinimum" in constraints:
        lines.append(f"    if (!({expr} > {repr(constraints['exclusiveMinimum'])})) {{ error = \"{label} must be > {constraints['exclusiveMinimum']}\"; return false; }}")
    if "exclusiveMaximum" in constraints:
        lines.append(f"    if (!({expr} < {repr(constraints['exclusiveMaximum'])})) {{ error = \"{label} must be < {constraints['exclusiveMaximum']}\"; return false; }}")
    if cpp_type == "std::string":
        if "minLength" in constraints:
            lines.append(f"    if ({expr}.size() < {int(constraints['minLength'])}U) {{ error = \"{label} is too short\"; return false; }}")
        if "maxLength" in constraints:
            lines.append(f"    if ({expr}.size() > {int(constraints['maxLength'])}U) {{ error = \"{label} is too long\"; return false; }}")
    return lines


def render_core(data: dict[str, Any]) -> str:
    lines = [HEADER.rstrip(), "", '#include "generated_options.hpp"', '#include "json_writer.hpp"', "", "#include <cmath>", "#include <ostream>", "#include <string>", "", "namespace aldous_tsp {", ""]
    p_values_option = next(option for option in data["options"] if option["id"] == "p_values")
    lines.append("std::vector<double> default_p_values() {")
    lines.append(f"    return {cpp_default(p_values_option)};")
    lines.append("}")
    lines.append("")
    lines.append("void apply_generated_cli_defaults(RunOptions& opt) {")
    for option in data["options"]:
        if option.get("declare", True) and "cli_default" in option:
            lines.append(f"    {access(option)} = {cpp_value(option, option['cli_default'])};")
    lines.append("}")
    lines.append("")
    lines.append("void apply_generated_quick_preset(RunOptions& opt) {")
    for option in data["options"]:
        if option.get("declare", True) and "quick_default" in option:
            lines.append(f"    {access(option)} = {cpp_value(option, option['quick_default'])};")
    lines.append("}")
    lines.append("")
    lines.append("bool validate_generated_option_ranges(const RunOptions& opt, std::string& error) {")
    for option in data["options"]:
        if not option.get("declare", True):
            continue
        expr = access(option)
        constraints = option.get("constraints", {})
        label = option.get("cli") or option.get("json_key") or option["id"]
        cpp_type = option["cpp_type"]
        if cpp_type in {"int", "double", "std::string"}:
            lines.extend(schema_check_expr(expr, constraints, label, cpp_type))
        elif cpp_type == "std::vector<double>":
            # Empty means "use default p grid" until runtime normalization.
            lines.append(f"    for (const double value : {expr}) {{")
            lines.append(f"        if (!std::isfinite(value) || !(value > 0.0 && value <= 1.0)) {{ error = \"{label} entries must be finite and in (0,1]\"; return false; }}")
            lines.append("    }")
        elif option.get("parser") and option.get("formatter"):
            lines.append("    {")
            lines.append(f"        {cpp_type} roundtrip{{}};")
            lines.append(f"        if (!{option['parser']}({option['formatter']}({expr}), roundtrip) || roundtrip != {expr}) {{")
            lines.append(f"            error = \"{label} has an invalid enum value\";")
            lines.append("            return false;")
            lines.append("        }")
            lines.append("    }")
    lines.append("    return true;")
    lines.append("}")
    lines.append("")
    lines.append("void write_generated_config(std::ostream& out, const RunOptions& opt, const std::string& indent) {")
    lines.append("    JsonWriter writer(out);")
    lines.append("    out << \"{\\n\";")
    emitted = [o for o in data["options"] if o.get("emit_json", True) and o.get("json_key") and (o.get("declare", True) or o.get("json_expr"))]
    for idx, option in enumerate(emitted):
        key = option["json_key"]
        expr = option.get("json_expr") or access(option)
        prefix = "" if idx == 0 else ","
        lines.append(f"    out << \"{prefix}\\n\" << indent << \"  \\\"{key}\\\": \";")
        cpp_type = option["cpp_type"]
        if option.get("formatter"):
            lines.append(f"    writer.string({option['formatter']}({expr}));")
        elif cpp_type == "bool":
            lines.append(f"    out << ({expr} ? \"true\" : \"false\");")
        elif cpp_type in {"int", "std::optional<int>"}:
            lines.append(f"    out << {expr};")
        elif cpp_type == "double":
            lines.append(f"    writer.number({expr});")
        elif cpp_type == "std::string":
            lines.append(f"    writer.string({expr});")
        elif cpp_type == "std::vector<double>":
            lines.append(f"    writer.double_array({expr});")
        else:
            fail(f"cannot emit JSON for {option['id']} type {cpp_type}")
    lines.append("    out << \"\\n\" << indent << \"}\";")
    lines.append("}")
    lines.append("")
    lines.append("} // namespace aldous_tsp")
    lines.append("")
    return "\n".join(lines)


def render_help(data: dict[str, Any]) -> str:
    section_names = {section["id"]: section["title"] for section in data["sections"]}
    chunks: list[str] = []
    for section in data["sections"]:
        chunks.append(section["title"] + ":")
        for option in data["options"]:
            if option["section"] != section["id"] or not option.get("cli"):
                continue
            label = option["cli"]
            if option.get("metavar"):
                label += " " + option["metavar"]
            elif option.get("cpp_type") == "bool" or option.get("action") in {"help", "self_test", "quick"}:
                label += "[=bool]"
            description = str(option.get("help", option["id"]))
            default = default_text(option)
            if default is not None:
                description += f" (default: {default})"
            wrapped = textwrap.wrap(description, width=82) or [""]
            chunks.append(f"  {label:<39} {wrapped[0]}")
            for continuation in wrapped[1:]:
                chunks.append(f"  {'':<39} {continuation}")
        chunks.append("")
    chunks.extend([
        "Boolean flags accept plain presence as true, or explicit =true/=false",
        "using true/false, yes/no, on/off, or 1/0.",
        "",
        "The generated option surfaces are checked in CI against config/options.json.",
    ])
    return "\n".join(chunks) + "\n"


def render_cli(data: dict[str, Any]) -> str:
    help_text = render_help(data)
    raw_delim = "ALDOUSHELP"
    if raw_delim in help_text:
        fail("help delimiter appears in generated text")
    lines = [HEADER.rstrip(), "", '#include "generated_options.hpp"', '#include "cli_internal.hpp"', "", "#include <algorithm>", "#include <cctype>", "#include <cstdio>", "#include <cstring>", "#include <string>", "", "namespace aldous_tsp {", "namespace {", ""]
    lines.extend(r'''bool parse_bool_value(const std::string& text, bool& out) {
    std::string normalized;
    normalized.reserve(text.size());
    for (const char raw : text) {
        const unsigned char ch = static_cast<unsigned char>(raw);
        normalized.push_back(static_cast<char>(std::tolower(ch)));
    }
    if (normalized == "1" || normalized == "true" || normalized == "yes" || normalized == "on") {
        out = true;
        return true;
    }
    if (normalized == "0" || normalized == "false" || normalized == "no" || normalized == "off") {
        out = false;
        return true;
    }
    return false;
}

bool bool_argument(const std::string& arg,
                   const std::string& flag,
                   bool& matched,
                   bool& value,
                   std::string& error) {
    matched = false;
    value = true;
    if (arg == flag) {
        matched = true;
        return true;
    }
    const std::string prefix = flag + "=";
    if (arg.rfind(prefix, 0) != 0) {
        return true;
    }
    matched = true;
    const std::string literal = arg.substr(prefix.size());
    if (!parse_bool_value(literal, value)) {
        error = "Invalid boolean value for " + flag + ": " + literal;
        return false;
    }
    return true;
}

bool value_argument(int& index,
                    int argc,
                    char** argv,
                    const std::string& flag,
                    std::string& value,
                    std::string& error) {
    const std::string arg = argv[index] != nullptr ? argv[index] : "";
    const std::string prefix = flag + "=";
    if (arg.rfind(prefix, 0) == 0) {
        value = arg.substr(prefix.size());
        return true;
    }
    if (index + 1 >= argc || argv[index + 1] == nullptr) {
        error = "missing value for " + flag;
        return false;
    }
    value = argv[++index];
    return true;
}

const char kGeneratedHelp[] = R"ALDOUSHELP('''.splitlines())
    lines.extend(help_text.rstrip("\n").splitlines())
    lines.append(f'){raw_delim}";')
    lines.extend(["", "} // namespace", ""])
    lines.append("void print_generated_help(FILE* stream, const char* argv0) {")
    lines.append("    FILE* destination = stream != nullptr ? stream : stdout;")
    lines.append("    const char* executable = (argv0 != nullptr && *argv0 != '\\0') ? argv0 : \"aldous_tsp\";")
    lines.append("    std::fprintf(destination, \"Usage: %s [options]\\n\\n\", executable);")
    lines.append("    std::fputs(kGeneratedHelp, destination);")
    lines.append("}")
    lines.append("")
    lines.append("bool generated_quick_requested(int argc, char** argv, bool& requested, std::string& error) {")
    lines.append("    requested = false;")
    lines.append("    for (int index = 1; index < argc; ++index) {")
    lines.append("        const std::string arg = argv[index] != nullptr ? argv[index] : \"\";")
    lines.append("        bool matched = false;")
    lines.append("        bool value = true;")
    lines.append("        if (!bool_argument(arg, \"--quick\", matched, value, error)) { return false; }")
    lines.append("        if (matched) { requested = value; }")
    lines.append("    }")
    lines.append("    return true;")
    lines.append("}")
    lines.append("")
    lines.append("GeneratedCliParseResult parse_generated_cli_option(int& index, int argc, char** argv, RunOptions& opt, bool& self_test, std::string& error) {")
    lines.append("    const std::string arg = (index >= 0 && index < argc && argv[index] != nullptr) ? argv[index] : \"\";")
    lines.append("    std::string flag = arg;")
    lines.append("    const std::size_t equals = flag.find('=');")
    lines.append("    if (equals != std::string::npos) { flag.resize(equals); }")
    for option in data["options"]:
        cli = option.get("cli")
        if not cli:
            continue
        action = option.get("action")
        cpp_type = option.get("cpp_type")
        aliases = [cli] + list(option.get("aliases", []))
        cond = " || ".join(f'flag == "{name}"' for name in aliases)
        # bool-like actions and fields parse against the actual alias spelling.
        if action in {"help", "self_test", "quick"} or cpp_type == "bool":
            lines.append(f"    if ({cond}) {{")
            lines.append("        bool matched = false;")
            lines.append("        bool value = true;")
            lines.append("        if (!bool_argument(arg, flag, matched, value, error)) { return GeneratedCliParseResult::Error; }")
            if action == "help":
                lines.append("        if (value) { print_generated_help(stdout, argc > 0 ? argv[0] : nullptr); return GeneratedCliParseResult::ExitSuccess; }")
            elif action == "self_test":
                lines.append("        self_test = value;")
            elif action == "quick":
                lines.append("        (void)value; // Preset was applied in the order-independent pre-scan.")
            else:
                expr = access(option)
                if option.get("invert"):
                    lines.append(f"        {expr} = !value;")
                else:
                    lines.append(f"        {expr} = value;")
            lines.append("        return GeneratedCliParseResult::Matched;")
            lines.append("    }")
            continue
        lines.append(f"    if ({cond}) {{")
        lines.append("        std::string value;")
        lines.append("        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }")
        if action == "p_values":
            lines.append("        if (!parse_p_values(value, opt.p_values)) { error = \"invalid --p-values: \" + value; return GeneratedCliParseResult::Error; }")
        elif action == "p_range":
            lines.append("        if (!parse_p_range(value, opt.p_values)) { error = \"invalid --p-range: \" + value; return GeneratedCliParseResult::Error; }")
        elif action == "p_file":
            lines.append("        if (!read_p_file(value, opt.p_values, error)) { return GeneratedCliParseResult::Error; }")
        else:
            expr = access(option)
            if cpp_type == "int":
                lines.append(f"        if (!parse_int(value, {expr})) {{ error = \"invalid integer for {cli}: \" + value; return GeneratedCliParseResult::Error; }}")
            elif cpp_type == "double":
                lines.append(f"        if (!parse_double(value, {expr})) {{ error = \"invalid floating-point value for {cli}: \" + value; return GeneratedCliParseResult::Error; }}")
            elif cpp_type == "std::string":
                lines.append(f"        {expr} = value;")
            elif cpp_type == "std::optional<int>":
                lines.append("        int parsed = 0;")
                lines.append(f"        if (!parse_int(value, parsed)) {{ error = \"invalid integer for {cli}: \" + value; return GeneratedCliParseResult::Error; }}")
                lines.append(f"        {expr} = parsed;")
            elif option.get("parser"):
                lines.append(f"        if (!{option['parser']}(value, {expr})) {{ error = \"invalid value for {cli}: \" + value; return GeneratedCliParseResult::Error; }}")
            else:
                fail(f"cannot generate parser for {option['id']}")
        lines.append("        return GeneratedCliParseResult::Matched;")
        lines.append("    }")
    lines.append("    return GeneratedCliParseResult::NoMatch;")
    lines.append("}")
    lines.append("")
    lines.append("} // namespace aldous_tsp")
    lines.append("")
    return "\n".join(lines)


def schema_property(option: dict[str, Any]) -> dict[str, Any]:
    constraints = copy.deepcopy(option.get("constraints", {}))
    if not constraints:
        cpp_type = option.get("cpp_type")
        if cpp_type == "bool": constraints = {"type": "boolean"}
        elif cpp_type in {"int", "std::optional<int>"}: constraints = {"type": "integer"}
        elif cpp_type == "double": constraints = {"type": "number"}
        elif cpp_type == "std::string": constraints = {"type": "string"}
    if option.get("help"):
        constraints["description"] = option["help"]
    if option.get("declare", True) and "default" in option:
        value = option["default"]
        if value is not None and option.get("id") not in {"point_seed", "search_seed"}:
            constraints["default"] = value
    return constraints


def render_schema(data: dict[str, Any]) -> str:
    schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    schema_version = int(data["schema_version"])
    version_property = schema["properties"]["schema_version"]
    version_property.clear()
    version_property.update({"type": "integer", "const": schema_version})
    properties: dict[str, Any] = {}
    required: list[str] = []
    for option in data["options"]:
        key = option.get("json_key")
        if not key:
            continue
        if option.get("emit_json", True) and (option.get("declare", True) or option.get("json_expr")):
            properties[key] = schema_property(option)
            if option.get("required", True):
                required.append(key)
        elif not option.get("declare", True) and option.get("required", True) and option.get("constraints"):
            properties[key] = schema_property(option)
            required.append(key)
    config = schema["$defs"]["config"]
    config["type"] = "object"
    config["required"] = required
    config["properties"] = properties
    config["additionalProperties"] = False
    return json.dumps(schema, indent=2, ensure_ascii=False) + "\n"


def render_docs(data: dict[str, Any]) -> str:
    section_names = {s["id"]: s["title"] for s in data["sections"]}
    lines = ["# Generated option reference", "", "This file is generated from `config/options.json`. Do not edit it directly.", ""]
    for section in data["sections"]:
        lines.extend([f"## {section['title']}", "", "| CLI option | JSON key | Default | Constraints | Description |", "|---|---|---:|---|---|"])
        for option in data["options"]:
            if option["section"] != section["id"] or not option.get("cli"):
                continue
            cli = f"`{option['cli']}`"
            key = f"`{option['json_key']}`" if option.get("json_key") else "—"
            default = default_text(option) or "—"
            constraints = option.get("constraints", {})
            constraint_text = ", ".join(f"{k}={v}" for k, v in constraints.items() if k != "type") or constraints.get("type", "—")
            description = str(option.get("help", "")).replace("|", "\\|")
            lines.append(f"| {cli} | {key} | `{default}` | {constraint_text} | {description} |")
        lines.append("")
    return "\n".join(lines)


def outputs(data: dict[str, Any]) -> dict[Path, str]:
    result = {
        path: {
            "oracle_fields": lambda: render_fields(data, "oracle"),
            "solver_fields": lambda: render_fields(data, "solver"),
            "run_fields": lambda: render_fields(data, "run"),
            "schema_version": lambda: HEADER + f"inline constexpr int kDefaultSchemaVersion = {int(data['schema_version'])};\n",
            "header": render_header,
            "core": lambda: render_core(data),
            "cli": lambda: render_cli(data),
            "docs": lambda: render_docs(data),
        }[kind]()
        for path, kind in GENERATED.items()
    }
    result[SCHEMA_PATH] = render_schema(data)
    return result


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if committed outputs are stale")
    args = parser.parse_args()
    data = load_metadata()
    generated = outputs(data)
    stale: list[str] = []
    for path, content in generated.items():
        if args.check:
            existing = path.read_text(encoding="utf-8") if path.exists() else None
            if existing != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if stale:
        print("generated option surfaces are stale:", file=sys.stderr)
        for path in stale:
            print(f"  {path}", file=sys.stderr)
        print("run: python3 scripts/generate_options.py", file=sys.stderr)
        return 1
    if not args.check:
        print(f"generated {len(generated)} files from {METADATA_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
