// Generated by scripts/generate_options.py from config/options.json. DO NOT EDIT.

#include "generated_options.hpp"
#include "json_writer.hpp"

#include <cmath>
#include <ostream>
#include <string>

namespace aldous_tsp {

std::vector<double> default_p_values() {
    return {0.02, 0.03, 0.05, 0.07, 0.1, 0.15, 0.2, 0.25, 0.3, 0.4, 0.5, 0.6, 0.8, 1.0};
}

void apply_generated_cli_defaults(RunOptions& opt) {
    opt.solver.restart_threads = 0;
}

void apply_generated_quick_preset(RunOptions& opt) {
    opt.N = 48;
    opt.instances = 2;
    opt.p_values = {0.1, 0.25, 0.5, 1.0};
    opt.solver.tsp_restarts = 1;
    opt.solver.tsp_ils = 20;
    opt.solver.tsp_patience = 8;
    opt.solver.subset_restarts = 1;
    opt.solver.sa_iters = 250;
    opt.solver.pair_exchange_passes = 0;
    opt.solver.ruin_recreate_rounds = 1;
    opt.solver.path_relink_top = 0;
}

bool validate_generated_option_ranges(const RunOptions& opt, std::string& error) {
    if (opt.N < 3) { error = "--N must be >= 3"; return false; }
    if (opt.instances < 1) { error = "--instances must be >= 1"; return false; }
    if (opt.threads < 0) { error = "--threads must be >= 0"; return false; }
    if (opt.cv_mc_samples < 1) { error = "--cv-mc-samples must be >= 1"; return false; }
    if (opt.hk_iterations < 1) { error = "--hk-iterations must be >= 1"; return false; }
    if (opt.campaign_id.size() < 1U) { error = "--campaign-id is too short"; return false; }
    if (opt.campaign_id.size() > 256U) { error = "--campaign-id is too long"; return false; }
    if (opt.campaign_shard < 0) { error = "--campaign-shard must be >= 0"; return false; }
    if (opt.replicate_offset < 0) { error = "--replicate-offset must be >= 0"; return false; }
    if (opt.solver_policy_id.size() < 1U) { error = "--solver-policy-id is too short"; return false; }
    if (opt.solver_policy_id.size() > 256U) { error = "--solver-policy-id is too long"; return false; }
    if (opt.fidelity_level.size() < 1U) { error = "--fidelity-level is too short"; return false; }
    if (opt.fidelity_level.size() > 256U) { error = "--fidelity-level is too long"; return false; }
    if (opt.output_path.size() < 1U) { error = "--output is too short"; return false; }
    if (opt.output_path.size() > 4096U) { error = "--output is too long"; return false; }
    {
        OutputDurability roundtrip{};
        if (!parse_output_durability(output_durability_name(opt.output_durability), roundtrip) || roundtrip != opt.output_durability) {
            error = "--output-durability has an invalid enum value";
            return false;
        }
    }
    for (const double value : opt.p_values) {
        if (!std::isfinite(value) || !(value > 0.0 && value <= 1.0)) { error = "p_values entries must be finite and in (0,1]"; return false; }
    }
    if (opt.solver.knn_k < 0) { error = "--knn must be >= 0"; return false; }
    {
        KnnBackend roundtrip{};
        if (!parse_knn_backend(knn_backend_name(opt.solver.knn_backend), roundtrip) || roundtrip != opt.solver.knn_backend) {
            error = "--knn-backend has an invalid enum value";
            return false;
        }
    }
    if (opt.solver.verify_knn_checks < 0) { error = "--verify-knn must be >= 0"; return false; }
    if (!std::isfinite(opt.solver.grid_cell)) { error = "--grid-cell must be finite"; return false; }
    if (opt.solver.grid_cell < 0) { error = "--grid-cell must be >= 0"; return false; }
    if (opt.solver.exact_subset_max_n < 0 || opt.solver.exact_subset_max_n > 18) { error = "--exact-subset-max-n must be in [0,18]"; return false; }
    if (opt.solver.tsp_candidate_starts < 1) { error = "--tsp-candidate-starts must be >= 1"; return false; }
    if (opt.solver.tsp_farthest_starts < 0 || opt.solver.tsp_farthest_starts > 1) { error = "--tsp-farthest-starts must be in [0,1]"; return false; }
    if (!std::isfinite(opt.solver.tsp_min_edge_jaccard)) { error = "--tsp-min-edge-jaccard must be finite"; return false; }
    if (opt.solver.tsp_min_edge_jaccard < 0 || opt.solver.tsp_min_edge_jaccard > 1) { error = "--tsp-min-edge-jaccard must be in [0,1]"; return false; }
    if (opt.solver.tsp_restarts < 1) { error = "--tsp-restarts must be >= 1"; return false; }
    if (opt.solver.tsp_ils < 0) { error = "--tsp-ils must be >= 0"; return false; }
    if (opt.solver.tsp_patience < 0) { error = "--tsp-patience must be >= 0"; return false; }
    if (opt.solver.subset_restarts < -1) { error = "--restarts must be >= -1"; return false; }
    if (opt.solver.continuation_restarts < 0) { error = "--continuation-restarts must be >= 0"; return false; }
    {
        ContinuationPolicy roundtrip{};
        if (!parse_continuation_policy(continuation_policy_name(opt.solver.continuation_policy), roundtrip) || roundtrip != opt.solver.continuation_policy) {
            error = "--continuation-policy has an invalid enum value";
            return false;
        }
    }
    if (opt.solver.racing_candidates < 0) { error = "--racing-candidates must be >= 0"; return false; }
    if (opt.solver.racing_survivors < 1) { error = "--racing-survivors must be >= 1"; return false; }
    if (opt.solver.racing_pilot_iters < 0) { error = "--racing-pilot-iters must be >= 0"; return false; }
    if (!std::isfinite(opt.solver.racing_min_jaccard)) { error = "--racing-min-jaccard must be finite"; return false; }
    if (opt.solver.racing_min_jaccard < 0 || opt.solver.racing_min_jaccard > 1) { error = "--racing-min-jaccard must be in [0,1]"; return false; }
    if (opt.solver.strong_polish_finalists < 1) { error = "--strong-polish-finalists must be >= 1"; return false; }
    if (!std::isfinite(opt.solver.strong_polish_min_jaccard)) { error = "--strong-polish-min-jaccard must be finite"; return false; }
    if (opt.solver.strong_polish_min_jaccard < 0 || opt.solver.strong_polish_min_jaccard > 1) { error = "--strong-polish-min-jaccard must be in [0,1]"; return false; }
    if (opt.solver.sa_iters < 0) { error = "--sa-iters must be >= 0"; return false; }
    if (opt.solver.sa_iters_per_k < 0) { error = "--sa-iters-per-k must be >= 0"; return false; }
    if (opt.solver.sa_iters_per_n < 0) { error = "--sa-iters-per-n must be >= 0"; return false; }
    if (opt.solver.sa_insertion_window < 1) { error = "--sa-insertion-window must be >= 1"; return false; }
    if (opt.solver.sa_spatial_neighbors < 1) { error = "--sa-spatial-neighbors must be >= 1"; return false; }
    if (!std::isfinite(opt.solver.region_dilation)) { error = "--region-dilation must be finite"; return false; }
    if (opt.solver.region_dilation < 1) { error = "--region-dilation must be >= 1"; return false; }
    if (opt.solver.subset_kick_restarts < 0) { error = "--kick-restarts must be >= 0"; return false; }
    if (!std::isfinite(opt.solver.kick_fraction)) { error = "--kick-fraction must be finite"; return false; }
    if (!(opt.solver.kick_fraction > 0)) { error = "--kick-fraction must be > 0"; return false; }
    if (!(opt.solver.kick_fraction < 1)) { error = "--kick-fraction must be < 1"; return false; }
    if (!std::isfinite(opt.solver.kick_t0)) { error = "--kick-t0 must be finite"; return false; }
    if (!(opt.solver.kick_t0 > 0)) { error = "--kick-t0 must be > 0"; return false; }
    if (!std::isfinite(opt.solver.sa_t0)) { error = "--sa-t0 must be finite"; return false; }
    if (!(opt.solver.sa_t0 > 0)) { error = "--sa-t0 must be > 0"; return false; }
    if (!std::isfinite(opt.solver.sa_t1)) { error = "--sa-t1 must be finite"; return false; }
    if (!(opt.solver.sa_t1 > 0)) { error = "--sa-t1 must be > 0"; return false; }
    if (opt.solver.restart_threads < 0) { error = "--restart-threads must be >= 0"; return false; }
    if (!std::isfinite(opt.solver.time_budget_per_p)) { error = "--time-budget-per-p must be finite"; return false; }
    if (opt.solver.time_budget_per_p < 0) { error = "--time-budget-per-p must be >= 0"; return false; }
    if (opt.solver.final_exhaustive_k < 0) { error = "--final-exhaustive-k must be >= 0"; return false; }
    {
        ExhaustiveTwoOptPolicy roundtrip{};
        if (!parse_exhaustive_two_opt_policy(exhaustive_two_opt_policy_name(opt.solver.exhaustive_two_opt_policy), roundtrip) || roundtrip != opt.solver.exhaustive_two_opt_policy) {
            error = "--exhaustive-two-opt-policy has an invalid enum value";
            return false;
        }
    }
    if (opt.solver.subset_swap_descent_passes < 0) { error = "--subset-swap-passes must be >= 0"; return false; }
    if (opt.solver.pair_exchange_passes < 0) { error = "--pair-exchange-passes must be >= 0"; return false; }
    if (opt.solver.pair_exchange_max_k < 0) { error = "--pair-exchange-max-k must be >= 0"; return false; }
    if (opt.solver.ruin_recreate_rounds < 0) { error = "--ruin-recreate-rounds must be >= 0"; return false; }
    if (!std::isfinite(opt.solver.ruin_recreate_max_fraction)) { error = "--ruin-recreate-max-fraction must be finite"; return false; }
    if (opt.solver.ruin_recreate_max_fraction < 0 || opt.solver.ruin_recreate_max_fraction > 1) { error = "--ruin-recreate-max-fraction must be in [0,1]"; return false; }
    if (opt.solver.ruin_recreate_max_nodes < 0) { error = "--ruin-recreate-max-nodes must be >= 0"; return false; }
    if (opt.solver.ruin_recreate_pool_cap < 1) { error = "--ruin-recreate-pool-cap must be >= 1"; return false; }
    if (opt.solver.ejection_chain_starts < 0) { error = "--ejection-chain-starts must be >= 0"; return false; }
    if (opt.solver.ejection_chain_depth < 0) { error = "--ejection-chain-depth must be >= 0"; return false; }
    if (opt.solver.ejection_chain_candidates < 0) { error = "--ejection-chain-candidates must be >= 0"; return false; }
    if (opt.solver.ejection_chain_remove_cap < 0) { error = "--ejection-chain-remove-cap must be >= 0"; return false; }
    if (!std::isfinite(opt.solver.ejection_chain_max_uphill)) { error = "--ejection-chain-max-uphill must be finite"; return false; }
    if (opt.solver.ejection_chain_max_uphill < 0) { error = "--ejection-chain-max-uphill must be >= 0"; return false; }
    if (opt.solver.elite_diversity_slots < 0) { error = "--elite-diversity-slots must be >= 0"; return false; }
    if (!std::isfinite(opt.solver.elite_min_jaccard)) { error = "--elite-min-jaccard must be finite"; return false; }
    if (opt.solver.elite_min_jaccard < 0 || opt.solver.elite_min_jaccard > 1) { error = "--elite-min-jaccard must be in [0,1]"; return false; }
    if (!std::isfinite(opt.solver.elite_quality_slack)) { error = "--elite-quality-slack must be finite"; return false; }
    if (opt.solver.elite_quality_slack < 0) { error = "--elite-quality-slack must be >= 0"; return false; }
    if (opt.solver.path_relink_top < 0) { error = "--path-relink-top must be >= 0"; return false; }
    if (opt.solver.path_relink_diverse_reserve < 0) { error = "--path-relink-diverse-reserve must be >= 0"; return false; }
    if (opt.solver.path_relink_max_pairs < 0) { error = "--path-relink-max-pairs must be >= 0"; return false; }
    if (opt.solver.path_relink_max_removed < 0) { error = "--path-relink-max-removed must be >= 0"; return false; }
    if (opt.solver.path_relink_max_removed_sum < 0) { error = "--path-relink-max-removed-sum must be >= 0"; return false; }
    if (opt.solver.path_relink_max_candidate_scans < 0) { error = "--path-relink-max-candidate-scans must be >= 0"; return false; }
    {
        SolverMode roundtrip{};
        if (!parse_solver_mode(solver_mode_name(opt.solver.mode), roundtrip) || roundtrip != opt.solver.mode) {
            error = "--mode has an invalid enum value";
            return false;
        }
    }
    {
        ExternalOracleMode roundtrip{};
        if (!parse_external_oracle_mode(external_oracle_mode_name(opt.solver.oracle.cfg.mode), roundtrip) || roundtrip != opt.solver.oracle.cfg.mode) {
            error = "--oracle has an invalid enum value";
            return false;
        }
    }
    {
        OracleProblemFormat roundtrip{};
        if (!parse_oracle_problem_format(oracle_problem_format_name(opt.solver.oracle.cfg.problem_format), roundtrip) || roundtrip != opt.solver.oracle.cfg.problem_format) {
            error = "--oracle-format has an invalid enum value";
            return false;
        }
    }
    if (opt.solver.oracle.cfg.lkh_path.size() < 1U) { error = "--lkh-path is too short"; return false; }
    if (opt.solver.oracle.cfg.lkh_path.size() > 4096U) { error = "--lkh-path is too long"; return false; }
    if (opt.solver.oracle.cfg.concorde_path.size() < 1U) { error = "--concorde-path is too short"; return false; }
    if (opt.solver.oracle.cfg.concorde_path.size() > 4096U) { error = "--concorde-path is too long"; return false; }
    if (opt.solver.oracle.cfg.time_limit_sec < 0) { error = "--oracle-time-limit must be >= 0"; return false; }
    if (opt.solver.oracle.cfg.scale < 1) { error = "--oracle-scale must be >= 1"; return false; }
    if (opt.solver.oracle.cfg.tsp_top < 0) { error = "--oracle-tsp-top must be >= 0"; return false; }
    if (opt.solver.oracle.cfg.subset_top < 0) { error = "--oracle-subset-top must be >= 0"; return false; }
    if (opt.solver.oracle.cfg.min_k < 3) { error = "--oracle-min-k must be >= 3"; return false; }
    if (opt.solver.oracle.cfg.max_k < 3) { error = "--oracle-max-k must be >= 3"; return false; }
    if (opt.solver.oracle.cfg.lkh_runs < 1) { error = "--oracle-lkh-runs must be >= 1"; return false; }
    if (opt.solver.oracle.cfg.lkh_max_trials < 0) { error = "--oracle-lkh-trials must be >= 0"; return false; }
    return true;
}

void write_generated_config(std::ostream& out, const RunOptions& opt, const std::string& indent) {
    JsonWriter writer(out);
    out << "{\n";
    out << "\n" << indent << "  \"N\": ";
    out << opt.N;
    out << ",\n" << indent << "  \"instances\": ";
    out << opt.instances;
    out << ",\n" << indent << "  \"threads\": ";
    out << opt.threads;
    out << ",\n" << indent << "  \"periodic\": ";
    out << (opt.periodic ? "true" : "false");
    out << ",\n" << indent << "  \"control_variate\": ";
    out << (opt.control_variate ? "true" : "false");
    out << ",\n" << indent << "  \"cv_mc_samples\": ";
    out << opt.cv_mc_samples;
    out << ",\n" << indent << "  \"held_karp\": ";
    out << (opt.held_karp ? "true" : "false");
    out << ",\n" << indent << "  \"hk_iterations\": ";
    out << opt.hk_iterations;
    out << ",\n" << indent << "  \"verbose\": ";
    out << (opt.verbose ? "true" : "false");
    out << ",\n" << indent << "  \"include_instance_rows\": ";
    out << (opt.include_instance_rows ? "true" : "false");
    out << ",\n" << indent << "  \"campaign_id\": ";
    writer.string(opt.campaign_id);
    out << ",\n" << indent << "  \"campaign_shard\": ";
    out << opt.campaign_shard;
    out << ",\n" << indent << "  \"replicate_offset\": ";
    out << opt.replicate_offset;
    out << ",\n" << indent << "  \"point_seed\": ";
    out << effective_point_seed(opt);
    out << ",\n" << indent << "  \"search_seed\": ";
    out << effective_search_seed(opt);
    out << ",\n" << indent << "  \"solver_policy_id\": ";
    writer.string(opt.solver_policy_id);
    out << ",\n" << indent << "  \"fidelity_level\": ";
    writer.string(opt.fidelity_level);
    out << ",\n" << indent << "  \"second_sweep\": ";
    out << (opt.second_sweep ? "true" : "false");
    out << ",\n" << indent << "  \"force_output\": ";
    out << (opt.force_output ? "true" : "false");
    out << ",\n" << indent << "  \"dry_run\": ";
    out << (opt.dry_run ? "true" : "false");
    out << ",\n" << indent << "  \"dump_config\": ";
    out << (opt.dump_config ? "true" : "false");
    out << ",\n" << indent << "  \"output_path\": ";
    writer.string(opt.output_path);
    out << ",\n" << indent << "  \"output_durability\": ";
    writer.string(output_durability_name(opt.output_durability));
    out << ",\n" << indent << "  \"p_values\": ";
    writer.double_array(opt.p_values);
    out << ",\n" << indent << "  \"knn_k\": ";
    out << opt.solver.knn_k;
    out << ",\n" << indent << "  \"knn_backend\": ";
    writer.string(knn_backend_name(opt.solver.knn_backend));
    out << ",\n" << indent << "  \"verify_knn_checks\": ";
    out << opt.solver.verify_knn_checks;
    out << ",\n" << indent << "  \"grid_cell\": ";
    writer.number(opt.solver.grid_cell);
    out << ",\n" << indent << "  \"exact_subset_max_n\": ";
    out << opt.solver.exact_subset_max_n;
    out << ",\n" << indent << "  \"tsp_candidate_starts\": ";
    out << opt.solver.tsp_candidate_starts;
    out << ",\n" << indent << "  \"tsp_farthest_starts\": ";
    out << opt.solver.tsp_farthest_starts;
    out << ",\n" << indent << "  \"tsp_min_edge_jaccard\": ";
    writer.number(opt.solver.tsp_min_edge_jaccard);
    out << ",\n" << indent << "  \"tsp_restarts\": ";
    out << opt.solver.tsp_restarts;
    out << ",\n" << indent << "  \"tsp_ils\": ";
    out << opt.solver.tsp_ils;
    out << ",\n" << indent << "  \"tsp_patience\": ";
    out << opt.solver.tsp_patience;
    out << ",\n" << indent << "  \"subset_restarts\": ";
    out << opt.solver.subset_restarts;
    out << ",\n" << indent << "  \"continuation_restarts\": ";
    out << opt.solver.continuation_restarts;
    out << ",\n" << indent << "  \"continuation_policy\": ";
    writer.string(continuation_policy_name(opt.solver.continuation_policy));
    out << ",\n" << indent << "  \"racing_candidates\": ";
    out << opt.solver.racing_candidates;
    out << ",\n" << indent << "  \"racing_survivors\": ";
    out << opt.solver.racing_survivors;
    out << ",\n" << indent << "  \"racing_pilot_iters\": ";
    out << opt.solver.racing_pilot_iters;
    out << ",\n" << indent << "  \"racing_min_jaccard\": ";
    writer.number(opt.solver.racing_min_jaccard);
    out << ",\n" << indent << "  \"staged_search\": ";
    out << (opt.solver.staged_search ? "true" : "false");
    out << ",\n" << indent << "  \"strong_polish_finalists\": ";
    out << opt.solver.strong_polish_finalists;
    out << ",\n" << indent << "  \"strong_polish_min_jaccard\": ";
    writer.number(opt.solver.strong_polish_min_jaccard);
    out << ",\n" << indent << "  \"sa_iters\": ";
    out << opt.solver.sa_iters;
    out << ",\n" << indent << "  \"sa_iters_per_k\": ";
    out << opt.solver.sa_iters_per_k;
    out << ",\n" << indent << "  \"sa_iters_per_n\": ";
    out << opt.solver.sa_iters_per_n;
    out << ",\n" << indent << "  \"sa_exact_insertion\": ";
    out << (opt.solver.sa_exact_insertion ? "true" : "false");
    out << ",\n" << indent << "  \"sa_insertion_window\": ";
    out << opt.solver.sa_insertion_window;
    out << ",\n" << indent << "  \"small_p_dense_fill\": ";
    out << (opt.solver.small_p_dense_fill ? "true" : "false");
    out << ",\n" << indent << "  \"exploration_exact_insertion\": ";
    out << (opt.solver.exploration_exact_insertion ? "true" : "false");
    out << ",\n" << indent << "  \"sa_spatial_insertion\": ";
    out << (opt.solver.sa_spatial_insertion ? "true" : "false");
    out << ",\n" << indent << "  \"dense_exact_insertion\": ";
    out << (opt.solver.dense_exact_insertion ? "true" : "false");
    out << ",\n" << indent << "  \"sa_spatial_neighbors\": ";
    out << opt.solver.sa_spatial_neighbors;
    out << ",\n" << indent << "  \"region_seeds\": ";
    out << (opt.solver.region_seeds ? "true" : "false");
    out << ",\n" << indent << "  \"region_dilation\": ";
    writer.number(opt.solver.region_dilation);
    out << ",\n" << indent << "  \"kick_restarts\": ";
    out << opt.solver.subset_kick_restarts;
    out << ",\n" << indent << "  \"kick_fraction\": ";
    writer.number(opt.solver.kick_fraction);
    out << ",\n" << indent << "  \"kick_t0\": ";
    writer.number(opt.solver.kick_t0);
    out << ",\n" << indent << "  \"sa_t0\": ";
    writer.number(opt.solver.sa_t0);
    out << ",\n" << indent << "  \"sa_t1\": ";
    writer.number(opt.solver.sa_t1);
    out << ",\n" << indent << "  \"restart_threads\": ";
    out << opt.solver.restart_threads;
    out << ",\n" << indent << "  \"time_budget_per_p\": ";
    writer.number(opt.solver.time_budget_per_p);
    out << ",\n" << indent << "  \"final_exhaustive_k\": ";
    out << opt.solver.final_exhaustive_k;
    out << ",\n" << indent << "  \"exhaustive_two_opt_policy\": ";
    writer.string(exhaustive_two_opt_policy_name(opt.solver.exhaustive_two_opt_policy));
    out << ",\n" << indent << "  \"subset_swap_descent_passes\": ";
    out << opt.solver.subset_swap_descent_passes;
    out << ",\n" << indent << "  \"pair_exchange_passes\": ";
    out << opt.solver.pair_exchange_passes;
    out << ",\n" << indent << "  \"pair_exchange_max_k\": ";
    out << opt.solver.pair_exchange_max_k;
    out << ",\n" << indent << "  \"ruin_recreate_rounds\": ";
    out << opt.solver.ruin_recreate_rounds;
    out << ",\n" << indent << "  \"adaptive_ruin_recreate\": ";
    out << (opt.solver.adaptive_ruin_recreate ? "true" : "false");
    out << ",\n" << indent << "  \"ruin_recreate_max_fraction\": ";
    writer.number(opt.solver.ruin_recreate_max_fraction);
    out << ",\n" << indent << "  \"ruin_recreate_max_nodes\": ";
    out << opt.solver.ruin_recreate_max_nodes;
    out << ",\n" << indent << "  \"ruin_recreate_pool_cap\": ";
    out << opt.solver.ruin_recreate_pool_cap;
    out << ",\n" << indent << "  \"ejection_chain_starts\": ";
    out << opt.solver.ejection_chain_starts;
    out << ",\n" << indent << "  \"ejection_chain_depth\": ";
    out << opt.solver.ejection_chain_depth;
    out << ",\n" << indent << "  \"ejection_chain_candidates\": ";
    out << opt.solver.ejection_chain_candidates;
    out << ",\n" << indent << "  \"ejection_chain_remove_cap\": ";
    out << opt.solver.ejection_chain_remove_cap;
    out << ",\n" << indent << "  \"ejection_chain_max_uphill\": ";
    writer.number(opt.solver.ejection_chain_max_uphill);
    out << ",\n" << indent << "  \"elite_diversity_slots\": ";
    out << opt.solver.elite_diversity_slots;
    out << ",\n" << indent << "  \"elite_min_jaccard\": ";
    writer.number(opt.solver.elite_min_jaccard);
    out << ",\n" << indent << "  \"elite_quality_slack\": ";
    writer.number(opt.solver.elite_quality_slack);
    out << ",\n" << indent << "  \"path_relink_top\": ";
    out << opt.solver.path_relink_top;
    out << ",\n" << indent << "  \"path_relink_diverse_reserve\": ";
    out << opt.solver.path_relink_diverse_reserve;
    out << ",\n" << indent << "  \"path_relink_max_pairs\": ";
    out << opt.solver.path_relink_max_pairs;
    out << ",\n" << indent << "  \"path_relink_max_removed\": ";
    out << opt.solver.path_relink_max_removed;
    out << ",\n" << indent << "  \"path_relink_max_removed_sum\": ";
    out << opt.solver.path_relink_max_removed_sum;
    out << ",\n" << indent << "  \"path_relink_max_candidate_scans\": ";
    out << opt.solver.path_relink_max_candidate_scans;
    out << ",\n" << indent << "  \"seed\": ";
    out << opt.solver.seed;
    out << ",\n" << indent << "  \"mode\": ";
    writer.string(solver_mode_name(opt.solver.mode));
    out << ",\n" << indent << "  \"disable_two_opt\": ";
    out << (opt.solver.disable_two_opt ? "true" : "false");
    out << ",\n" << indent << "  \"disable_or_opt\": ";
    out << (opt.solver.disable_or_opt ? "true" : "false");
    out << ",\n" << indent << "  \"disable_subset_swap\": ";
    out << (opt.solver.disable_subset_swap ? "true" : "false");
    out << ",\n" << indent << "  \"disable_pair_exchange\": ";
    out << (opt.solver.disable_pair_exchange ? "true" : "false");
    out << ",\n" << indent << "  \"disable_elite_restarts\": ";
    out << (opt.solver.disable_elite_restarts ? "true" : "false");
    out << ",\n" << indent << "  \"disable_ruin_recreate\": ";
    out << (opt.solver.disable_ruin_recreate ? "true" : "false");
    out << ",\n" << indent << "  \"disable_ejection_chain\": ";
    out << (opt.solver.disable_ejection_chain ? "true" : "false");
    out << ",\n" << indent << "  \"disable_path_relink\": ";
    out << (opt.solver.disable_path_relink ? "true" : "false");
    out << ",\n" << indent << "  \"disable_smallp_seeds\": ";
    out << (opt.solver.disable_smallp_seeds ? "true" : "false");
    out << ",\n" << indent << "  \"disable_highp_delete\": ";
    out << (opt.solver.disable_highp_delete ? "true" : "false");
    out << ",\n" << indent << "  \"oracle_mode\": ";
    writer.string(external_oracle_mode_name(opt.solver.oracle.cfg.mode));
    out << ",\n" << indent << "  \"oracle_format\": ";
    writer.string(oracle_problem_format_name(opt.solver.oracle.cfg.problem_format));
    out << ",\n" << indent << "  \"lkh_path\": ";
    writer.string(opt.solver.oracle.cfg.lkh_path);
    out << ",\n" << indent << "  \"concorde_path\": ";
    writer.string(opt.solver.oracle.cfg.concorde_path);
    out << ",\n" << indent << "  \"oracle_time_limit_sec\": ";
    out << opt.solver.oracle.cfg.time_limit_sec;
    out << ",\n" << indent << "  \"oracle_scale\": ";
    out << opt.solver.oracle.cfg.scale;
    out << ",\n" << indent << "  \"oracle_tsp_top\": ";
    out << opt.solver.oracle.cfg.tsp_top;
    out << ",\n" << indent << "  \"oracle_subset_top\": ";
    out << opt.solver.oracle.cfg.subset_top;
    out << ",\n" << indent << "  \"oracle_min_k\": ";
    out << opt.solver.oracle.cfg.min_k;
    out << ",\n" << indent << "  \"oracle_max_k\": ";
    out << opt.solver.oracle.cfg.max_k;
    out << ",\n" << indent << "  \"oracle_lkh_runs\": ";
    out << opt.solver.oracle.cfg.lkh_runs;
    out << ",\n" << indent << "  \"oracle_lkh_max_trials\": ";
    out << opt.solver.oracle.cfg.lkh_max_trials;
    out << ",\n" << indent << "  \"oracle_use_for_tsp\": ";
    out << (opt.solver.oracle.cfg.use_for_tsp ? "true" : "false");
    out << ",\n" << indent << "  \"oracle_use_for_subset\": ";
    out << (opt.solver.oracle.cfg.use_for_subset ? "true" : "false");
    out << ",\n" << indent << "  \"oracle_inline_feedback\": ";
    out << (opt.solver.oracle.cfg.inline_feedback ? "true" : "false");
    out << ",\n" << indent << "  \"oracle_verbose\": ";
    out << (opt.solver.oracle.cfg.verbose ? "true" : "false");
    out << ",\n" << indent << "  \"oracle_resolved\": ";
    writer.string(resolved_oracle_mode_name(opt.solver.oracle.resolved));
    out << ",\n" << indent << "  \"oracle_exec_path\": ";
    writer.string(opt.solver.oracle.exec_path);
    out << ",\n" << indent << "  \"oracle_version\": ";
    writer.string(opt.solver.oracle.version);
    out << "\n" << indent << "}";
}

} // namespace aldous_tsp
