// Generated by scripts/generate_options.py from config/options.json. DO NOT EDIT.
#pragma once

#include "aldous_tsp/config.hpp"

#include <cstdio>
#include <iosfwd>
#include <string>

namespace aldous_tsp {

enum class GeneratedCliParseResult {
    NoMatch,
    Matched,
    Error,
    ExitSuccess,
};

// Generated CLI parser. It is side-effect free except for mutating `opt`,
// setting `self_test`, and writing generated help for --help.
GeneratedCliParseResult parse_generated_cli_option(
    int& index,
    int argc,
    char** argv,
    RunOptions& opt,
    bool& self_test,
    std::string& error);

bool generated_quick_requested(int argc, char** argv, bool& requested, std::string& error);
void apply_generated_cli_defaults(RunOptions& opt);
void apply_generated_quick_preset(RunOptions& opt);
void print_generated_help(FILE* stream, const char* argv0);

// Generated field-local validation. Cross-field and instance-dependent rules
// live in validation.cpp and call this function first.
bool validate_generated_option_ranges(const RunOptions& opt, std::string& error);

// Emits the complete user-controlled configuration object. Runtime resolution
// fields such as oracle_exec_path are appended by results.cpp.
void write_generated_config(std::ostream& out, const RunOptions& opt, const std::string& indent);

} // namespace aldous_tsp
