// Generated by scripts/generate_options.py from config/options.json. DO NOT EDIT.

#include "generated_options.hpp"
#include "cli_internal.hpp"

#include <algorithm>
#include <cctype>
#include <cstdio>
#include <cstring>
#include <string>

namespace aldous_tsp {
namespace {

bool parse_bool_value(const std::string& text, bool& out) {
    std::string normalized;
    normalized.reserve(text.size());
    for (const char raw : text) {
        const unsigned char ch = static_cast<unsigned char>(raw);
        normalized.push_back(static_cast<char>(std::tolower(ch)));
    }
    if (normalized == "1" || normalized == "true" || normalized == "yes" || normalized == "on") {
        out = true;
        return true;
    }
    if (normalized == "0" || normalized == "false" || normalized == "no" || normalized == "off") {
        out = false;
        return true;
    }
    return false;
}

bool bool_argument(const std::string& arg,
                   const std::string& flag,
                   bool& matched,
                   bool& value,
                   std::string& error) {
    matched = false;
    value = true;
    if (arg == flag) {
        matched = true;
        return true;
    }
    const std::string prefix = flag + "=";
    if (arg.rfind(prefix, 0) != 0) {
        return true;
    }
    matched = true;
    const std::string literal = arg.substr(prefix.size());
    if (!parse_bool_value(literal, value)) {
        error = "Invalid boolean value for " + flag + ": " + literal;
        return false;
    }
    return true;
}

bool value_argument(int& index,
                    int argc,
                    char** argv,
                    const std::string& flag,
                    std::string& value,
                    std::string& error) {
    const std::string arg = argv[index] != nullptr ? argv[index] : "";
    const std::string prefix = flag + "=";
    if (arg.rfind(prefix, 0) == 0) {
        value = arg.substr(prefix.size());
        return true;
    }
    if (index + 1 >= argc || argv[index + 1] == nullptr) {
        error = "missing value for " + flag;
        return false;
    }
    value = argv[++index];
    return true;
}

const char kGeneratedHelp[] = R"ALDOUSHELP(
General:
  --help[=bool]                           Show this generated help text and exit.
  --self-test[=bool]                      Run built-in smoke and self tests.
  --quick[=bool]                          Apply the small fast-run preset; explicit flags override it regardless of order.
  --verbose-p[=bool]                      Print per-instance and per-p progress. (default: false)
  --force[=bool]                          Replace an existing output path. (default: false)
  --dry-run[=bool]                        Validate and print the resolved configuration without solving. (default: false)
  --dump-config[=bool]                    Print the resolved configuration before solving. (default: false)
  --output <file>                         Output JSON path. (default: results.json)
  --output-durability <mode>              Output durability: none, file, or full (file plus parent directory). (default:
                                          full)

Simulation and campaign identity:
  --N <int>                               Number of random points. (default: 500)
  --instances <int>                       Monte Carlo point-set instances. (default: 15)
  --threads <int>                         Instance worker threads; zero selects an automatic bounded value. (default: 0)
  --memory-budget-mb <MiB>                Conservative peak-memory budget in MiB; zero derives a safe automatic budget from
                                          currently available physical/container memory. (default: 0)
  --periodic[=bool]                       Use flat-torus periodic boundary conditions. (default: false)
  --campaign-id <text>                    Stable campaign identity. (default: default)
  --campaign-shard <int>                  Nonnegative campaign shard identity. (default: 0)
  --replicate-offset <int>                Campaign-global first replicate identifier. (default: 0)
  --point-seed <int>                      Point-instance seed; defaults to --seed. (default: --seed)
  --search-seed <int>                     Heuristic-search seed; defaults to --seed. (default: --seed)
  --solver-policy-id <text>               Stable solver-policy identity. (default: default)
  --fidelity-level <text>                 Fidelity identity such as cheap or strong. (default: strong)
  --p-values <csv>                        Comma-separated p grid, for example 0.02,0.05,1.
  --p-range <a:b:n>                       Linear p grid from a to b with n values.
  --p-file <file>                         Read whitespace- or comma-separated p values from a file.
  --seed <int>                            Base random seed. (default: 2024)

Subset search:
  --second-sweep[=bool]                   Run an ascending continuation sweep after the descending sweep. (default: false)
  --exact-subset-max-n <int>              Globally solve subset choice and tour when N is at most this threshold; zero
                                          disables it. (default: 0)
  --search-policy <name>                  Search controller preset. legacy-balanced preserves the 0.10 controller. heldout-
                                          balanced uses the held-out four-candidate SA policy through p=0.35; heldout-
                                          quality uses a deeper policy, extends periodic runs through p=0.50, and
                                          strengthens full-TSP screening. Explicit core SA or TSP population controls take
                                          precedence. (default: legacy-balanced)
  --restarts <int>                        Subset restarts; -1 selects the p-aware automatic policy. (default: -1)
  --continuation-restarts <int>           Warm restarts when a neighboring-p parent exists. (default: 1)
  --continuation-policy <name>            Continuation policy: supplemental or fixed-budget. (default: supplemental)
  --racing-candidates <int>               Supplemental candidates screened by deterministic restart racing; zero disables
                                          it. (default: 0)
  --racing-survivors <int>                Pilot candidates promoted to a full-depth rerun. (default: 2)
  --racing-pilot-iters <int>              SA iterations used to screen each race candidate. (default: 2000)
  --racing-min-jaccard <float>            Preferred selected-set Jaccard distance between promoted race candidates.
                                          (default: 0.05)
  --staged-search[=bool]                  Reserve expensive post-SA neighborhoods for promoted finalists. (default: true)
  --strong-polish-finalists <int>         Finalists receiving the strong search stage. (default: 3)
  --strong-polish-min-jaccard <float>     Preferred selected-set distance among strong-polish finalists. (default: 0.02)
  --sa-iters <int>                        Base subset-SA iteration budget. (default: 60000)
  --sa-iters-per-k <int>                  Additional SA iterations per selected node k. (default: 0)
  --sa-iters-per-n <int>                  Additional SA iterations per candidate point N. (default: 0)
  --sa-exact-insertion[=bool]             Use the historical exact O(k) insertion scan for every SA move. (default: false)
  --sa-insertion-window <int>             Tour-position radius for windowed SA insertion. (default: 12)
  --small-p-dense-fill[=bool]             At small p, fill the restart pool with dense-seed variants instead of uncontracted
                                          random subsets. (default: true)
  --exploration-exact-insertion[=bool]    Use exact insertion for spread-out exploration seeds. (default: true)
  --sa-spatial-insertion[=bool]           Use insertion slots from a live spatial index (default: false).
  --dense-exact-insertion[=bool]          Force exact insertion on dense seeds; this reproduces the old bit-identical path
                                          at k=2000 but costs about +58% wall. (default: false)
  --sa-spatial-neighbors <int>            Nearest current members allowed to offer insertion slots. (default: 16)
  --region-seeds[=bool]                   Use localized region seeds in the explorer pool. (default: false)
  --region-dilation <float>               Region-seed candidate dilation. (default: 3.0)
  --kick-restarts <int>                   Scheduled elite-kick restarts. (default: 0)
  --kick-fraction <float>                 Fraction of members swapped by an elite kick. (default: 0.1)
  --kick-t0 <float>                       SA start temperature for elite-kick restarts. (default: 0.35)
  --sa-t0 <float>                         Fixed SA start temperature. (default: 1.4)
  --sa-t1 <float>                         Fixed SA end temperature. (default: 5e-05)
  --sa-auto-temperature[=bool]            Calibrate each restart's SA temperatures from sampled uphill move deltas.
                                          (default: false)
  --sa-temperature-samples <int>          Target positive-delta samples for restart-local SA calibration. (default: 256)
  --sa-temperature-quantile <float>       Positive-delta quantile used to calibrate SA endpoints. (default: 0.5)
  --sa-initial-uphill-acceptance <float>  Target initial acceptance for the calibrated uphill-delta quantile. (default: 0.6)
  --sa-final-uphill-acceptance <float>    Target final acceptance for the calibrated uphill-delta quantile. (default: 0.01)
  --sa-candidate-trials <int>             Candidate swaps evaluated per SA iteration; one preserves the historical proposal.
                                          (default: 1)
  --sa-multiple-try-random-probability <float> For multiple-try SA, probability of selecting a random valid trial instead of the
                                          best. (default: 0.1)
  --restart-threads <int>                 Parallel subset-restart workers; zero requests automatic allocation. (default: 1)
  --time-budget-per-p <sec>               Wall-clock target per instance/p solve; zero disables anytime mode. (default: 0.0)
  --mode <name>                           Solver mode: balanced, smallp-region, highp-delete, or hybrid. (default: balanced)

Full-TSP search:
  --tsp-candidate-starts <int>            Cheap deterministic TSP starts screened before ILS promotion. (default: 12)
  --tsp-farthest-starts <0|1>             Opt into at most one cubic farthest-insertion pilot. (default: 0)
  --tsp-min-edge-jaccard <float>          Preferred edge-Jaccard distance among promoted TSP starts. (default: 0.02)
  --tsp-restarts <int>                    Full TSP restarts promoted into ILS. (default: 5)
  --tsp-ils <int>                         Full-TSP ILS perturbation iterations. (default: 300)
  --tsp-patience <int>                    Full-TSP ILS stagnation patience. (default: 80)

Local-search neighborhoods:
  --final-exhaustive-k <int>              Exhaustive final 2-opt cardinality threshold. (default: 300)
  --exhaustive-two-opt-policy <name>      Exhaustive 2-opt policy: never, final-only, or all-polish. (default: final-only)
  --subset-swap-passes <int>              Deterministic one-for-one subset-swap passes. (default: 1)
  --pair-exchange-passes <int>            Two-for-two subset-exchange passes. (default: 1)
  --pair-exchange-max-k <int>             Skip pair exchange above k; zero removes the gate. (default: 5000)
  --ruin-recreate-rounds <int>            Ruin/recreate LNS rounds. (default: 4)
  --adaptive-ruin-recreate[=bool]         Use the adaptive multi-scale ruin/recreate operator portfolio. (default: true)
  --ruin-recreate-max-fraction <float>    Maximum ruined fraction of k. (default: 0.05)
  --ruin-recreate-max-nodes <int>         Absolute ruin-size cap; zero removes it. (default: 96)
  --ruin-recreate-pool-cap <int>          Candidate repair-pool cap. (default: 640)
  --ejection-chain-starts <int>           Variable-depth membership-chain starts per restart. (default: 3)
  --ejection-chain-depth <int>            Maximum membership swaps per ejection chain. (default: 6)
  --ejection-chain-candidates <int>       Incoming-node candidates per chain step. (default: 24)
  --ejection-chain-remove-cap <int>       Removable selected-node cap per chain step; zero means all. (default: 96)
  --ejection-chain-max-uphill <float>     Maximum cumulative uphill excursion in mean-edge units. (default: 0.75)
  --elite-diversity-slots <int>           Supplemental set-diverse elite slots. (default: 4)
  --elite-min-jaccard <float>             Minimum selected-set Jaccard distance for supplemental elite entries. (default:
                                          0.02)
  --elite-quality-slack <float>           Quality slack allowed for supplemental diverse entries. (default: 0.03)
  --path-relink-top <int>                 Literal maximum archive population exposed to relinking. (default: 3)
  --path-relink-diverse-reserve <int>     Diversity-preferred entries inside the relinking node cap. (default: 1)
  --path-relink-max-pairs <int>           Maximum ranked relinking pair attempts; zero is unlimited. (default: 3)
  --path-relink-max-removed <int>         Maximum one-way selected-set difference per pair; zero is unlimited. (default: 64)
  --path-relink-max-removed-sum <int>     Cumulative selected-set-difference budget; zero is unlimited. (default: 128)
  --path-relink-max-candidate-scans <int> Exact relinking candidate-scan budget; zero is unlimited. (default: 250000)

Geometry and KNN:
  --knn <int>                             Exact KNN candidate count; values are capped to N-1. (default: 40)
  --knn-backend <name>                    Exact KNN backend: grid or bruteforce. (default: grid)
  --reverse-knn[=bool]                    Build reverse-KNN adjacency lazily when candidate local search needs it; disable
                                          to save additional memory. (default: true)
  --verify-knn <int>                      Sampled exact-KNN verification checks. (default: 0)
  --grid-cell <float>                     Force a grid cell size; zero selects an automatic safe value. (default: 0.0)

Statistical diagnostics:
  --control-variate[=bool]                Compute the two-nearest-neighbor control variate and fixed-subset bound; the bound
                                          measures tour quality conditional on that subset. (default: false)
  --cv-mc-samples <int>                   Cheap KNN-only samples used to estimate the full-set control-variate expectation.
                                          (default: 2000)
  --held-karp[=bool]                      Compute the Held-Karp lower bound for each selected subset; this certifies tour
                                          quality conditional on that subset, not global subset optimality. (default: false)
  --hk-iterations <int>                   Held-Karp subgradient iterations. (default: 400)
  --include-instance-rows[=bool]          Include per-instance rows and restart diagnostics in JSON. (default: false)

External oracle:
  --oracle <mode>                         External oracle: none, auto, lkh, or concorde. (default: none)
  --oracle-format <format>                Oracle problem format: matrix or euc2d. (default: matrix)
  --lkh-path <path>                       LKH executable path. (default: LKH)
  --concorde-path <path>                  Concorde executable path. (default: concorde)
  --oracle-time-limit <sec>               Per-call oracle time limit; zero disables it. (default: 0)
  --oracle-scale <int>                    Distance scaling factor for integer oracle matrices. (default: 1000000)
  --oracle-tsp-top <int>                  Top full-TSP solutions sent to the oracle. (default: 1)
  --oracle-subset-top <int>               Top subset solutions sent to the oracle. (default: 1)
  --oracle-min-k <int>                    Minimum cardinality eligible for an external oracle. (default: 17)
  --oracle-max-k <int>                    Maximum cardinality eligible for an external oracle. (default: 2500)
  --oracle-lkh-runs <int>                 LKH RUNS parameter. (default: 6)
  --oracle-lkh-trials <int>               LKH MAX_TRIALS; zero uses the solver default. (default: 0)
  --oracle-no-tsp[=bool]                  Disable external-oracle use for full TSP. (default: true)
  --oracle-no-subset[=bool]               Disable external-oracle use for subset tours. (default: true)
  --oracle-inline-feedback[=bool]         Feed oracle-improved cycles back into the in-process elite search. (default:
                                          false)
  --oracle-verbose[=bool]                 Print external-oracle diagnostics. (default: false)

Ablation controls:
  --disable-two-opt[=bool]                Disable 2-opt. (default: false)
  --disable-or-opt[=bool]                 Disable Or-opt. (default: false)
  --disable-subset-swap[=bool]            Disable one-for-one subset swaps. (default: false)
  --disable-pair-exchange[=bool]          Disable two-for-two subset exchange. (default: false)
  --disable-elite-restarts[=bool]         Disable elite-seeded anytime restarts. (default: false)
  --disable-ruin-recreate[=bool]          Disable ruin/recreate. (default: false)
  --disable-ejection-chain[=bool]         Disable membership ejection chains. (default: false)
  --disable-path-relink[=bool]            Disable path relinking. (default: false)
  --disable-smallp-seeds[=bool]           Disable specialized small-p seeds. (default: false)
  --disable-highp-delete[=bool]           Disable high-p deletion seeds and exchange. (default: false)

Boolean flags accept plain presence as true, or explicit =true/=false
using true/false, yes/no, on/off, or 1/0.

The generated option surfaces are checked in CI against config/options.json.
)ALDOUSHELP";

} // namespace

void print_generated_help(FILE* stream, const char* argv0) {
    FILE* destination = stream != nullptr ? stream : stdout;
    const char* executable = (argv0 != nullptr && *argv0 != '\0') ? argv0 : "aldous_tsp";
    std::fprintf(destination, "Usage: %s [options]\n\n", executable);
    std::fputs(kGeneratedHelp, destination);
}

bool generated_quick_requested(int argc, char** argv, bool& requested, std::string& error) {
    requested = false;
    for (int index = 1; index < argc; ++index) {
        const std::string arg = argv[index] != nullptr ? argv[index] : "";
        bool matched = false;
        bool value = true;
        if (!bool_argument(arg, "--quick", matched, value, error)) { return false; }
        if (matched) { requested = value; }
    }
    return true;
}

GeneratedCliParseResult parse_generated_cli_option(int& index, int argc, char** argv, RunOptions& opt, bool& self_test, std::string& error) {
    const std::string arg = (index >= 0 && index < argc && argv[index] != nullptr) ? argv[index] : "";
    std::string flag = arg;
    const std::size_t equals = flag.find('=');
    if (equals != std::string::npos) { flag.resize(equals); }
    if (flag == "--help") {
        bool matched = false;
        bool value = true;
        if (!bool_argument(arg, flag, matched, value, error)) { return GeneratedCliParseResult::Error; }
        if (value) { print_generated_help(stdout, argc > 0 ? argv[0] : nullptr); return GeneratedCliParseResult::ExitSuccess; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--self-test") {
        bool matched = false;
        bool value = true;
        if (!bool_argument(arg, flag, matched, value, error)) { return GeneratedCliParseResult::Error; }
        self_test = value;
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--quick") {
        bool matched = false;
        bool value = true;
        if (!bool_argument(arg, flag, matched, value, error)) { return GeneratedCliParseResult::Error; }
        (void)value; // Preset was applied in the order-independent pre-scan.
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--N") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.N)) { error = "invalid integer for --N: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--instances") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.instances)) { error = "invalid integer for --instances: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--threads") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.threads)) { error = "invalid integer for --threads: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--memory-budget-mb") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.memory_budget_mb)) { error = "invalid integer for --memory-budget-mb: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--periodic") {
        bool matched = false;
        bool value = true;
        if (!bool_argument(arg, flag, matched, value, error)) { return GeneratedCliParseResult::Error; }
        opt.periodic = value;
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--control-variate") {
        bool matched = false;
        bool value = true;
        if (!bool_argument(arg, flag, matched, value, error)) { return GeneratedCliParseResult::Error; }
        opt.control_variate = value;
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--cv-mc-samples") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.cv_mc_samples)) { error = "invalid integer for --cv-mc-samples: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--held-karp") {
        bool matched = false;
        bool value = true;
        if (!bool_argument(arg, flag, matched, value, error)) { return GeneratedCliParseResult::Error; }
        opt.held_karp = value;
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--hk-iterations") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.hk_iterations)) { error = "invalid integer for --hk-iterations: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--verbose-p") {
        bool matched = false;
        bool value = true;
        if (!bool_argument(arg, flag, matched, value, error)) { return GeneratedCliParseResult::Error; }
        opt.verbose = value;
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--include-instance-rows") {
        bool matched = false;
        bool value = true;
        if (!bool_argument(arg, flag, matched, value, error)) { return GeneratedCliParseResult::Error; }
        opt.include_instance_rows = value;
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--campaign-id") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        opt.campaign_id = value;
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--campaign-shard") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.campaign_shard)) { error = "invalid integer for --campaign-shard: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--replicate-offset") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.replicate_offset)) { error = "invalid integer for --replicate-offset: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--point-seed") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        int parsed = 0;
        if (!parse_int(value, parsed)) { error = "invalid integer for --point-seed: " + value; return GeneratedCliParseResult::Error; }
        opt.point_seed = parsed;
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--search-seed") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        int parsed = 0;
        if (!parse_int(value, parsed)) { error = "invalid integer for --search-seed: " + value; return GeneratedCliParseResult::Error; }
        opt.search_seed = parsed;
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--solver-policy-id") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        opt.solver_policy_id = value;
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--fidelity-level") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        opt.fidelity_level = value;
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--second-sweep") {
        bool matched = false;
        bool value = true;
        if (!bool_argument(arg, flag, matched, value, error)) { return GeneratedCliParseResult::Error; }
        opt.second_sweep = value;
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--force") {
        bool matched = false;
        bool value = true;
        if (!bool_argument(arg, flag, matched, value, error)) { return GeneratedCliParseResult::Error; }
        opt.force_output = value;
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--dry-run") {
        bool matched = false;
        bool value = true;
        if (!bool_argument(arg, flag, matched, value, error)) { return GeneratedCliParseResult::Error; }
        opt.dry_run = value;
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--dump-config") {
        bool matched = false;
        bool value = true;
        if (!bool_argument(arg, flag, matched, value, error)) { return GeneratedCliParseResult::Error; }
        opt.dump_config = value;
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--output") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        opt.output_path = value;
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--output-durability") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_output_durability(value, opt.output_durability)) { error = "invalid value for --output-durability: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--p-values") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_p_values(value, opt.p_values)) { error = "invalid --p-values: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--p-range") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_p_range(value, opt.p_values)) { error = "invalid --p-range: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--p-file") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!read_p_file(value, opt.p_values, error)) { return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--knn") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.knn_k)) { error = "invalid integer for --knn: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--knn-backend") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_knn_backend(value, opt.solver.knn_backend)) { error = "invalid value for --knn-backend: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--reverse-knn") {
        bool matched = false;
        bool value = true;
        if (!bool_argument(arg, flag, matched, value, error)) { return GeneratedCliParseResult::Error; }
        opt.solver.reverse_knn = value;
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--verify-knn") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.verify_knn_checks)) { error = "invalid integer for --verify-knn: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--grid-cell") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_double(value, opt.solver.grid_cell)) { error = "invalid floating-point value for --grid-cell: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--exact-subset-max-n") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.exact_subset_max_n)) { error = "invalid integer for --exact-subset-max-n: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--tsp-candidate-starts") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.tsp_candidate_starts)) { error = "invalid integer for --tsp-candidate-starts: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--tsp-farthest-starts") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.tsp_farthest_starts)) { error = "invalid integer for --tsp-farthest-starts: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--tsp-min-edge-jaccard") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_double(value, opt.solver.tsp_min_edge_jaccard)) { error = "invalid floating-point value for --tsp-min-edge-jaccard: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--tsp-restarts") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.tsp_restarts)) { error = "invalid integer for --tsp-restarts: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--tsp-ils") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.tsp_ils)) { error = "invalid integer for --tsp-ils: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--tsp-patience") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.tsp_patience)) { error = "invalid integer for --tsp-patience: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--search-policy") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_search_policy_preset(value, opt.solver.search_policy_preset)) { error = "invalid value for --search-policy: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--restarts") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.subset_restarts)) { error = "invalid integer for --restarts: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--continuation-restarts") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.continuation_restarts)) { error = "invalid integer for --continuation-restarts: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--continuation-policy") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_continuation_policy(value, opt.solver.continuation_policy)) { error = "invalid value for --continuation-policy: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--racing-candidates") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.racing_candidates)) { error = "invalid integer for --racing-candidates: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--racing-survivors") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.racing_survivors)) { error = "invalid integer for --racing-survivors: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--racing-pilot-iters") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.racing_pilot_iters)) { error = "invalid integer for --racing-pilot-iters: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--racing-min-jaccard") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_double(value, opt.solver.racing_min_jaccard)) { error = "invalid floating-point value for --racing-min-jaccard: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--staged-search") {
        bool matched = false;
        bool value = true;
        if (!bool_argument(arg, flag, matched, value, error)) { return GeneratedCliParseResult::Error; }
        opt.solver.staged_search = value;
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--strong-polish-finalists") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.strong_polish_finalists)) { error = "invalid integer for --strong-polish-finalists: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--strong-polish-min-jaccard") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_double(value, opt.solver.strong_polish_min_jaccard)) { error = "invalid floating-point value for --strong-polish-min-jaccard: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--sa-iters") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.sa_iters)) { error = "invalid integer for --sa-iters: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--sa-iters-per-k") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.sa_iters_per_k)) { error = "invalid integer for --sa-iters-per-k: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--sa-iters-per-n") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.sa_iters_per_n)) { error = "invalid integer for --sa-iters-per-n: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--sa-exact-insertion") {
        bool matched = false;
        bool value = true;
        if (!bool_argument(arg, flag, matched, value, error)) { return GeneratedCliParseResult::Error; }
        opt.solver.sa_exact_insertion = value;
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--sa-insertion-window") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.sa_insertion_window)) { error = "invalid integer for --sa-insertion-window: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--small-p-dense-fill") {
        bool matched = false;
        bool value = true;
        if (!bool_argument(arg, flag, matched, value, error)) { return GeneratedCliParseResult::Error; }
        opt.solver.small_p_dense_fill = value;
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--exploration-exact-insertion") {
        bool matched = false;
        bool value = true;
        if (!bool_argument(arg, flag, matched, value, error)) { return GeneratedCliParseResult::Error; }
        opt.solver.exploration_exact_insertion = value;
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--sa-spatial-insertion") {
        bool matched = false;
        bool value = true;
        if (!bool_argument(arg, flag, matched, value, error)) { return GeneratedCliParseResult::Error; }
        opt.solver.sa_spatial_insertion = value;
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--dense-exact-insertion") {
        bool matched = false;
        bool value = true;
        if (!bool_argument(arg, flag, matched, value, error)) { return GeneratedCliParseResult::Error; }
        opt.solver.dense_exact_insertion = value;
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--sa-spatial-neighbors") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.sa_spatial_neighbors)) { error = "invalid integer for --sa-spatial-neighbors: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--region-seeds") {
        bool matched = false;
        bool value = true;
        if (!bool_argument(arg, flag, matched, value, error)) { return GeneratedCliParseResult::Error; }
        opt.solver.region_seeds = value;
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--region-dilation") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_double(value, opt.solver.region_dilation)) { error = "invalid floating-point value for --region-dilation: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--kick-restarts") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.subset_kick_restarts)) { error = "invalid integer for --kick-restarts: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--kick-fraction") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_double(value, opt.solver.kick_fraction)) { error = "invalid floating-point value for --kick-fraction: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--kick-t0") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_double(value, opt.solver.kick_t0)) { error = "invalid floating-point value for --kick-t0: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--sa-t0") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_double(value, opt.solver.sa_t0)) { error = "invalid floating-point value for --sa-t0: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--sa-t1") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_double(value, opt.solver.sa_t1)) { error = "invalid floating-point value for --sa-t1: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--sa-auto-temperature") {
        bool matched = false;
        bool value = true;
        if (!bool_argument(arg, flag, matched, value, error)) { return GeneratedCliParseResult::Error; }
        opt.solver.sa_auto_temperature = value;
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--sa-temperature-samples") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.sa_temperature_samples)) { error = "invalid integer for --sa-temperature-samples: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--sa-temperature-quantile") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_double(value, opt.solver.sa_temperature_quantile)) { error = "invalid floating-point value for --sa-temperature-quantile: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--sa-initial-uphill-acceptance") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_double(value, opt.solver.sa_initial_uphill_acceptance)) { error = "invalid floating-point value for --sa-initial-uphill-acceptance: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--sa-final-uphill-acceptance") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_double(value, opt.solver.sa_final_uphill_acceptance)) { error = "invalid floating-point value for --sa-final-uphill-acceptance: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--sa-candidate-trials") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.sa_candidate_trials)) { error = "invalid integer for --sa-candidate-trials: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--sa-multiple-try-random-probability") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_double(value, opt.solver.sa_multiple_try_random_probability)) { error = "invalid floating-point value for --sa-multiple-try-random-probability: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--restart-threads") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.restart_threads)) { error = "invalid integer for --restart-threads: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--time-budget-per-p") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_double(value, opt.solver.time_budget_per_p)) { error = "invalid floating-point value for --time-budget-per-p: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--final-exhaustive-k") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.final_exhaustive_k)) { error = "invalid integer for --final-exhaustive-k: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--exhaustive-two-opt-policy") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_exhaustive_two_opt_policy(value, opt.solver.exhaustive_two_opt_policy)) { error = "invalid value for --exhaustive-two-opt-policy: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--subset-swap-passes") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.subset_swap_descent_passes)) { error = "invalid integer for --subset-swap-passes: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--pair-exchange-passes") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.pair_exchange_passes)) { error = "invalid integer for --pair-exchange-passes: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--pair-exchange-max-k") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.pair_exchange_max_k)) { error = "invalid integer for --pair-exchange-max-k: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--ruin-recreate-rounds") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.ruin_recreate_rounds)) { error = "invalid integer for --ruin-recreate-rounds: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--adaptive-ruin-recreate") {
        bool matched = false;
        bool value = true;
        if (!bool_argument(arg, flag, matched, value, error)) { return GeneratedCliParseResult::Error; }
        opt.solver.adaptive_ruin_recreate = value;
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--ruin-recreate-max-fraction") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_double(value, opt.solver.ruin_recreate_max_fraction)) { error = "invalid floating-point value for --ruin-recreate-max-fraction: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--ruin-recreate-max-nodes") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.ruin_recreate_max_nodes)) { error = "invalid integer for --ruin-recreate-max-nodes: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--ruin-recreate-pool-cap") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.ruin_recreate_pool_cap)) { error = "invalid integer for --ruin-recreate-pool-cap: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--ejection-chain-starts") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.ejection_chain_starts)) { error = "invalid integer for --ejection-chain-starts: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--ejection-chain-depth") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.ejection_chain_depth)) { error = "invalid integer for --ejection-chain-depth: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--ejection-chain-candidates") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.ejection_chain_candidates)) { error = "invalid integer for --ejection-chain-candidates: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--ejection-chain-remove-cap") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.ejection_chain_remove_cap)) { error = "invalid integer for --ejection-chain-remove-cap: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--ejection-chain-max-uphill") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_double(value, opt.solver.ejection_chain_max_uphill)) { error = "invalid floating-point value for --ejection-chain-max-uphill: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--elite-diversity-slots") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.elite_diversity_slots)) { error = "invalid integer for --elite-diversity-slots: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--elite-min-jaccard") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_double(value, opt.solver.elite_min_jaccard)) { error = "invalid floating-point value for --elite-min-jaccard: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--elite-quality-slack") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_double(value, opt.solver.elite_quality_slack)) { error = "invalid floating-point value for --elite-quality-slack: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--path-relink-top") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.path_relink_top)) { error = "invalid integer for --path-relink-top: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--path-relink-diverse-reserve") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.path_relink_diverse_reserve)) { error = "invalid integer for --path-relink-diverse-reserve: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--path-relink-max-pairs") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.path_relink_max_pairs)) { error = "invalid integer for --path-relink-max-pairs: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--path-relink-max-removed") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.path_relink_max_removed)) { error = "invalid integer for --path-relink-max-removed: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--path-relink-max-removed-sum") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.path_relink_max_removed_sum)) { error = "invalid integer for --path-relink-max-removed-sum: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--path-relink-max-candidate-scans") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.path_relink_max_candidate_scans)) { error = "invalid integer for --path-relink-max-candidate-scans: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--seed") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.seed)) { error = "invalid integer for --seed: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--mode") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_solver_mode(value, opt.solver.mode)) { error = "invalid value for --mode: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--disable-two-opt") {
        bool matched = false;
        bool value = true;
        if (!bool_argument(arg, flag, matched, value, error)) { return GeneratedCliParseResult::Error; }
        opt.solver.disable_two_opt = value;
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--disable-or-opt") {
        bool matched = false;
        bool value = true;
        if (!bool_argument(arg, flag, matched, value, error)) { return GeneratedCliParseResult::Error; }
        opt.solver.disable_or_opt = value;
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--disable-subset-swap") {
        bool matched = false;
        bool value = true;
        if (!bool_argument(arg, flag, matched, value, error)) { return GeneratedCliParseResult::Error; }
        opt.solver.disable_subset_swap = value;
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--disable-pair-exchange") {
        bool matched = false;
        bool value = true;
        if (!bool_argument(arg, flag, matched, value, error)) { return GeneratedCliParseResult::Error; }
        opt.solver.disable_pair_exchange = value;
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--disable-elite-restarts") {
        bool matched = false;
        bool value = true;
        if (!bool_argument(arg, flag, matched, value, error)) { return GeneratedCliParseResult::Error; }
        opt.solver.disable_elite_restarts = value;
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--disable-ruin-recreate") {
        bool matched = false;
        bool value = true;
        if (!bool_argument(arg, flag, matched, value, error)) { return GeneratedCliParseResult::Error; }
        opt.solver.disable_ruin_recreate = value;
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--disable-ejection-chain") {
        bool matched = false;
        bool value = true;
        if (!bool_argument(arg, flag, matched, value, error)) { return GeneratedCliParseResult::Error; }
        opt.solver.disable_ejection_chain = value;
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--disable-path-relink") {
        bool matched = false;
        bool value = true;
        if (!bool_argument(arg, flag, matched, value, error)) { return GeneratedCliParseResult::Error; }
        opt.solver.disable_path_relink = value;
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--disable-smallp-seeds") {
        bool matched = false;
        bool value = true;
        if (!bool_argument(arg, flag, matched, value, error)) { return GeneratedCliParseResult::Error; }
        opt.solver.disable_smallp_seeds = value;
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--disable-highp-delete") {
        bool matched = false;
        bool value = true;
        if (!bool_argument(arg, flag, matched, value, error)) { return GeneratedCliParseResult::Error; }
        opt.solver.disable_highp_delete = value;
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--oracle") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_external_oracle_mode(value, opt.solver.oracle.cfg.mode)) { error = "invalid value for --oracle: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--oracle-format") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_oracle_problem_format(value, opt.solver.oracle.cfg.problem_format)) { error = "invalid value for --oracle-format: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--lkh-path") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        opt.solver.oracle.cfg.lkh_path = value;
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--concorde-path") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        opt.solver.oracle.cfg.concorde_path = value;
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--oracle-time-limit") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.oracle.cfg.time_limit_sec)) { error = "invalid integer for --oracle-time-limit: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--oracle-scale") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.oracle.cfg.scale)) { error = "invalid integer for --oracle-scale: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--oracle-tsp-top") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.oracle.cfg.tsp_top)) { error = "invalid integer for --oracle-tsp-top: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--oracle-subset-top") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.oracle.cfg.subset_top)) { error = "invalid integer for --oracle-subset-top: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--oracle-min-k") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.oracle.cfg.min_k)) { error = "invalid integer for --oracle-min-k: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--oracle-max-k") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.oracle.cfg.max_k)) { error = "invalid integer for --oracle-max-k: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--oracle-lkh-runs") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.oracle.cfg.lkh_runs)) { error = "invalid integer for --oracle-lkh-runs: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--oracle-lkh-trials") {
        std::string value;
        if (!value_argument(index, argc, argv, flag, value, error)) { return GeneratedCliParseResult::Error; }
        if (!parse_int(value, opt.solver.oracle.cfg.lkh_max_trials)) { error = "invalid integer for --oracle-lkh-trials: " + value; return GeneratedCliParseResult::Error; }
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--oracle-no-tsp") {
        bool matched = false;
        bool value = true;
        if (!bool_argument(arg, flag, matched, value, error)) { return GeneratedCliParseResult::Error; }
        opt.solver.oracle.cfg.use_for_tsp = !value;
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--oracle-no-subset") {
        bool matched = false;
        bool value = true;
        if (!bool_argument(arg, flag, matched, value, error)) { return GeneratedCliParseResult::Error; }
        opt.solver.oracle.cfg.use_for_subset = !value;
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--oracle-inline-feedback") {
        bool matched = false;
        bool value = true;
        if (!bool_argument(arg, flag, matched, value, error)) { return GeneratedCliParseResult::Error; }
        opt.solver.oracle.cfg.inline_feedback = value;
        return GeneratedCliParseResult::Matched;
    }
    if (flag == "--oracle-verbose") {
        bool matched = false;
        bool value = true;
        if (!bool_argument(arg, flag, matched, value, error)) { return GeneratedCliParseResult::Error; }
        opt.solver.oracle.cfg.verbose = value;
        return GeneratedCliParseResult::Matched;
    }
    return GeneratedCliParseResult::NoMatch;
}

} // namespace aldous_tsp
